version: '3.8'

services:
  ai-image-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-image-generator
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - N8N_WEBHOOK_URL=$N8N_WEBHOOK_URL
      - CALLBACK_BASE_URL=$CALLBACK_BASE_URL
    restart: unless-stopped
    networks:
      - ai-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  # Optional: Include n8n service for development
  # Uncomment if you want to run n8n alongside the app
  # n8n:
  #   image: n8nio/n8n:latest
  #   container_name: n8n
  #   ports:
  #     - "5678:5678"
  #   environment:
  #     - N8N_BASIC_AUTH_ACTIVE=true
  #     - N8N_BASIC_AUTH_USER=admin
  #     - N8N_BASIC_AUTH_PASSWORD=admin123
  #   volumes:
  #     - n8n_data:/home/node/.n8n
  #   restart: unless-stopped
  #   networks:
  #     - ai-network

networks:
  ai-network:
    driver: bridge

# volumes:
#   n8n_data: